nginx:  
  image: prooph/nginx:www
  ports:
      - "8080:80"
      - "443:443"
      # these ports are for Zend Z-Ray
      - "10081:10081"
      - "10082:10082"
  links:
    - php:php
  volumes_from:
    - dataphp

php:  
  image: prooph/php:7.0-fpm
  links:
    - mariadb:mariadb
  volumes_from:
    - dataphp

dataphp:  
  image: debian:jessie
  volumes:
    - ./:/var/www

mariadb:  
  image: mariadb
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_USER=homestead
    - MYSQL_PASSWORD=secret
    - MYSQL_DATABASE=tutora

redis:
  image: redis
  ports:
    - "6379:6379"

mailcatcher:
  image: yappabe/mailcatcher
  ports:
    - "1025:1025"
    - "1080:1080"